networks:
  deploy:


services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"

    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - deploy


  backend:
    build:
      context: ./service
    networks:
      - deploy

  frontend:
    build:
      context: ./client
    networks:
      - deploy